//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse_MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int IdClient { get; set; }
        public string BadgeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdBDE { get; set; }
        public double Balance { get; set; }
        public int Passkey { get; set; }
    }
}
