//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse_MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int IdSale { get; set; }
        public Nullable<int> IdUser { get; set; }
        public int IdProduct { get; set; }
        public int Quantity { get; set; }
        public int IdBuyingBDE { get; set; }
        public System.DateTime SaleDate { get; set; }
    }
}
