//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse_MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int IdSale { get; set; }
        public Nullable<int> IdUser { get; set; }
        public int IdProduct { get; set; }
        public int Quantity { get; set; }
        public int IdBuyingBDE { get; set; }
        public System.DateTime SaleDate { get; set; }
        public Nullable<int> IdClient { get; set; }
    }
}
