//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse_MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produit()
        {
            this.historique = new HashSet<historique>();
        }
    
        public int idProduit { get; set; }
        public string nom { get; set; }
        public long quantite { get; set; }
        public string categorie { get; set; }
        public Nullable<System.DateTime> datePeremption { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historique> historique { get; set; }
    }
}
