//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse_MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IdUser { get; set; }
        public string Name { get; set; }
        public string PersonnalPassword { get; set; }
        public string BadgeID { get; set; }
        public int IdBDE { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActive { get; set; }
    }
}
