//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCaisse_MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public utilisateur()
        {
            this.historique = new HashSet<historique>();
        }
    
        public int idUtilisateur { get; set; }
        public string nom { get; set; }
        public string codePersonnel { get; set; }
        public string codeBadge { get; set; }
        public int idBde { get; set; }
        public bool admin { get; set; }
        public bool active { get; set; }
    
        public virtual BDE bde { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historique> historique { get; set; }
    }
}
